입점신청페이지 TextFileds, Selection controls(Radio Button, DropDown) UI 작업
YAPP-Github/21st-ALL-Rounder-Team-1-Web pull request #17
Opened 2023-01-01 19:48 UTC by say-young516

## 📎 Related Issues

- close #14

<br />

## 📋 작업 내용

- [x] TextFields 컴포넌트(일반)
- [ ] TextFields 컴포넌트(사업자등록번호)
- [x] RadioButton
- [x] DropDown 버튼

<br />

## 🔎 PR Point

일단 미리 올려놓고 한꺼번에 적겠읍니다..

<br />

## 😡 Trouble Shooting

- (이 작업을 하던 중에 발생했던 것)

<br />

## 👀 스크린샷 / GIF / 링크

- 내용을 입력해주세요.

<br />

## ➕ 추가적인 태스크

- 내용을 입력해주세요.

<br />

## 📚 Reference

- 내용을 입력해주세요.

<br />

## ✅ PR Submit 이전에 확인하세요 !

`체크리스트`

- [x] Merge 하는 브랜치에 Master/Main 브랜치가 아닙니다. (개인 작업시에만 확인)
- [x] Critical 한 Error 또는 Warning 이 존재하지 않습니다. 
- [x] 브라우저에 console 이 존재하지 않습니다.

2023-01-02 12:01 UTC, youngminss commented
알수도 있겠지만 Pull Request Draft 로 PR 등록이 가능하니까 다음부턴 사용해보세요 😁

2023-01-02 15:16 UTC, say-young516 commented
> 알수도 있겠지만 Pull Request Draft 로 PR 등록이 가능하니까 다음부턴 사용해보세요 😁

감사합니당 ~ 조금 덜 끝낸 부분들 마저 끝내고 내일 빅터가 퇴근하고 볼 수 있도록 올려놓으께요 ~

2023-01-03 08:05 UTC, say-young516 commented
@youngminss  pr 제대로 적어놨고, 트러블 슈팅 내용 혹시 떠오르는 해결방법이 있다면 공유부탁드립니다 (┬┬﹏┬┬)

2023-01-03 16:37 UTC, youngminss requested changes
전반적으로 코드를 확인해보려 노력했습니다

샐리가 PR Description 에 언급한 비즈니스 로직에 대한 코멘트는 텍스트로만 봐서는 잘 이해가 안가서 코멘트를 한 것은 거의 없습니다

대부분 코드 컨벤션에 대한 피드백 ? 정도의 코멘트가 주를 이루는 것 같네요 :)

고생하셨고, 추가적인 작업이 필요한 것 같아서 일단은 Request Change 하겠습니다.
추가적인 작업을 하거나 제가 남긴 코멘트에 대한 변경사항이 필요하다면 진행해보면 좋을 것 같습니다 !

샐리만 현재 문제라고 생각하는 비즈니스 로직에 대한 것은 구두로 이야기 해보면서 같이 고민해보죠 ~ 👍


ps. 현재 PR 이전에 제가 작업했던 코드들이 함께 PR 에 포함되었네요 ? 그래서 PR 분량이 엄청 많았다고 처음에 생각했던 것 같아요 (왜 일까요,,? 샐리가 push 하기전에 가장 최근 develop 브랜치를 pull 하고 push 했을 텐데,,)

2023-01-03 16:37 UTC, youngminss commented on components/feature/DropDownList/index.tsx
> +	const [selectedElement, setSelectedElement] = useState<number>(0); // 지금 선택된 항목
컴포넌트 이름과 연관지어 잠시 생각하고 나서, 이 변수 이름이 무엇을 의미하는지 (아마, 드롭다운 내 현재 선택되어있는 아이템의 아이디 ? 인덱스 ? 정도로 파악) 알게 되었습니다

조금 더 직관적인 네이밍을 고려해보면 어떨지 의견드립니다 ~

예를 들어 위에서 언급한 것처럼, 현재 `숫자` 가 데이터인것으로 보아, 드롭다운 내 `아이템 인덱스` 정보일 가능성이 커보이는데 `selectedElementIndex` 라던지

더 구체적인 의미로 생각해서 `드롭다운 내 현재 선택된 아이템 인덱스` 라면 `currentSelectedElementIndex` 로 이름이 조금 길 수 있으나, 더 명확한 네이밍이 좋을 수 있단 생각입니다 !

2023-01-03 16:37 UTC, youngminss commented on components/feature/DropDownList/index.tsx
> +				{dropdownElements.map((elementValue: string, idx: number) => {
일단, 단순한 케이스가 아니라면 배열 데이터에 대해 map 함수를 돌리며 컴포넌트를 렌더링하는 방식은 `지양` 하는 것이 좋은 것으로 알고있습니다 

해당 map 을 돌리기위한 `데이터` 에서 id 에 사용할 index 정보를 넣어서 사용하면, map 함수를 돌릴 때 자체적으로 제공하는 index 정보를 사용하지 않아도 될 것 같네요 ~

더구나, 이어지는 아래 코드에서는 map 함수 자체에서 제공하는 index 정보를 가지고 `비즈니스 로직` 이 이뤄지고 있는데 이런 경우는 더구나 더 `지양` 하는 것이 좋을 것 같단 의견입니다 !

2023-01-03 16:37 UTC, youngminss commented on components/feature/Button/RadioBtn/styled.ts
> +	& > input {
이것과 더불어서, 전반적으로 nested style 이 필요할 때 
tag 에 직접 접근하여 주입하는 스타일링은 `지양` 하는 것이 좋다고 알고 있습니다 !

물론, css-in-js 라이브러리를 통해 나름의 런타임 단계에서 className 이 부여되고 이에 해당하는 스타일링이 스코프를 지키며 적용이 되겠지만

Global 하게 태그에 설정하는 스타일과 충돌될 가능성이 있을  수 있다고 하더라구요 ~

그래서 저도 이런 방식을 실제로 사용도 했었고, 그 이후로는 차라리 className 을 일부러 명시한다던지의 차안책으로 방향성을 틀어서 사용하고 있습니다 !

2023-01-04 14:11 UTC, say-young516 commented on components/feature/BusinessLicenseTextField/index.tsx
> +	const [currentKey, setCurrentKey] = useState<string>('');
> 간단한 원시타입 데이터에 대한 타입은 저는 생략하는 편인데 샐리 생각도 궁금하네요 ~

나두 생략했다가 걍  typescript 기분 낼려고 이번 브랜치에서 함 다 바꿔봤어요 ㅋㅋㅋ.. 대충 아래 리뷰 훑어보니 컨벤션에 관한 이야기가 있던데 포함해서 주말에 얘기 함 해보죠

2023-01-04 14:12 UTC, say-young516 commented on components/feature/BusinessLicenseTextField/index.tsx
> +}
> 아직도 Lint 때문에 type 키워드가 interface 키워드로 자동 변환되나요 ?
> 
> 아니라면 저번에 언급했던 것처럼 컴포넌트 내부에서의 타입은 type 키워드를 사용해보는 건 어떨까요 ~ ?

앗 아마 이 뒤 커밋에 `type`으로 모두 바꿔놨을텐데 리뷰 반영할 때 한 번 더 보겠슴니다

2023-01-04 14:13 UTC, say-young516 commented on components/feature/Button/ProductImageBtn/index.tsx
> +			{/* <ProductErrorMeassage>사진을 입력하세요</ProductErrorMeassage> */}
> 주석 처리한 이유가 궁금하네요 ~ ?

이거 저번에 빅터랑 만났을 때 보여준다고요,, 어차피 이미지 버튼은 수정 및 추가구현사항이 많아서 error 처리를 따로 해두지 않았거든요

2023-01-04 14:15 UTC, say-young516 commented on components/feature/Button/RadioBtn/styled.ts
> +// }
> 앞으로는 특별한 이유가 있는 것이 아니라면 주석은 제거한 후에 PR 을 올려보면 좋을 것 같아요 ~
> 
> TODO 주석 등을 사용해보면 의미있을 것 같아요 ~ 최근에 알게되었고 사용해보면 좋을 것 같은데, TODO 주석과 같이 우리만의 Anchor Flag 를 주석에 포함해서 예를 들어 다음과 같은 (`TODO :: 내용`) 주석이 해당하더라구요 ~
> 
> ESLint 에 rule 을 추가하는 것도 방법이겠네요 ~

아 이 부분도 제거에선 지웠는데 커밋을 안 올렸나보네여 ~ TODO 의 내용이 잘 이해가 되지 않는데 혹시 이 [링크](https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=dotnethelper&logNo=60183048269)의 내용을 말하는 건가요? 처음 보는 내용이라 한 번 살펴봐야겠네용

2023-01-04 14:48 UTC, say-young516 commented on components/feature/Button/RadioBtn/styled.ts
> +	& > input {
> 

이 부분 먼가 잘 와닿지 않아서 만나서 이야기해보면 조을 것 같아여

2023-01-04 14:52 UTC, say-young516 commented on components/feature/DropDownList/index.tsx
> +				{dropdownElements.map((elementValue: string, idx: number) => {
> 일단, 단순한 케이스가 아니라면 배열 데이터에 대해 map 함수를 돌리며 컴포넌트를 렌더링하는 방식은 `지양` 하는 것이 좋은 것으로 알고있습니다
> 
> 해당 map 을 돌리기위한 `데이터` 에서 id 에 사용할 index 정보를 넣어서 사용하면, map 함수를 돌릴 때 자체적으로 제공하는 index 정보를 사용하지 않아도 될 것 같네요 ~
> 
> 더구나, 이어지는 아래 코드에서는 map 함수 자체에서 제공하는 index 정보를 가지고 `비즈니스 로직` 이 이뤄지고 있는데 이런 경우는 더구나 더 `지양` 하는 것이 좋을 것 같단 의견입니다 !

어엉 그래여? 저는 

1. 안에 들어가는 요소가 여러개인데, 이것이 유동적으로 변할 가능성이 있다 (그래서 props로 요소들애 대한 배열을 받는다)
2. 여러개 요소들이 같은 스타일링을 가지며 배치된다

이 두가지 중에 하나라도 해당된다면 주로 map을 사용해왔었거든요 ~ (해당 부분은 dropdown list로, 1,2번 둘 다 충족하는 컴포넌트네용) 이 컴포넌트 외에도 반복적인 스타일링이 있다면 map을 사용할 예정이었는데 어떤 식으로 바꾸는 게 조을까요? 같은 스타일링은 그냥 반복해서 적으면 되지만, props로 배열을 받는 컴포넌트에서는 map 을 이용한 방법밖에는 떠오르지 않아서요 (´。＿。｀)

2023-01-04 14:53 UTC, say-young516 commented on components/feature/DropDownList/index.tsx
> +const DropDownList = ({ dropdownElements }: Props) => {
> 이것도 한번 쯤 언급해보면 좋을 것 같아서, 물론 저도 개인적으로 지키려고 했으며, 최근에 다니고 있는 사내 코드 컨벤션 Rule 을 확인하면서 적응해보려 하는 코드 컨벤션입니다.
> 
> 타입 선언 - 컴포넌트 함수 시작 간에 경계에는 `개행` 을 한 줄 넣어 구분한다. 던지
> 
> 컴포넌트 함수 내에서도 예를 들면
> 
> 순서는
> 
> 1. 데이터 (const 상수와 같은)
> 2. 상태
> 3. 핸들러 함수
> 4. 사이드 이펙트 함수 (useEffect 같은 Hook)
> 5. return 문 (보통, jsx 문단)
> 
> 순으로 작성을 하며, 이들 사이에도 구분을 위해 `개행` 을 넣는 것처럼요 ~
> 
> 그리고 jsx 내 html 간에도 이것이 적용됩니다. 의미적으로 밀집되어 있지 않는 컴포넌트 or 태그 간에도 개행을 한 줄 넣어주는 것 처럼요 ~
> 
> 참고하면 좋을 것 같고, 지키면 더 좋을 것 같아요 ~

네엡 저두 이전 프로젝트에서는 순서를 지켰던 터라~ 한 번 이야기하고 정리해놓으려고 했었어요! 주말에 위에 import 문이랑 같이 정리해보는 거 어떠신지요

2023-01-04 15:25 UTC, youngminss commented on components/feature/Button/RadioBtn/styled.ts
> +// }
첨부해준 링크는 VS 기준으로 설명한거 같긴한데, 맞는거 같아요 ~

2023-01-04 15:32 UTC, youngminss commented on components/feature/DropDownList/index.tsx
> +				{dropdownElements.map((elementValue: string, idx: number) => {
map 을 안돌린다는 것이 아니라, 지금 코드에서 map 함수를 돌리면 예를 들어

```ts
// 위에서 샐리가 사용한 방식
const members = [
  { 
    name: "빅터",
    age: 28,
  },
  {
    name: "샐리",
    age: 100,
  }
];

members.map((member, idx) => console.log(idx, member.name));  // map 함수에서 제공하는 idx 값을 사용함


// 빅터가 말하고자 한 것
const members = [
  { 
    id: 0,
    name: "빅터",
    age: 28,
  },
  {
    id: 1,
    name: "샐리",
    age: 100,
  }
];

members.map(member => console.log(member.idx, member.name));  // map 함수에서 제공하는 idx 를 사용하지 않음
```

이런 의미로 코멘트 준거였어요 ~

2023-01-04 16:22 UTC, say-young516 commented on components/feature/DropDownList/index.tsx
> +				{dropdownElements.map((elementValue: string, idx: number) => {
> map 을 안돌린다는 것이 아니라, 지금 코드에서 map 함수를 돌리면 예를 들어
> 
> ```ts
> // 위에서 샐리가 사용한 방식
> const members = [
>   { 
>     name: "빅터",
>     age: 28,
>   },
>   {
>     name: "샐리",
>     age: 100,
>   }
> ];
> 
> members.map((member, idx) => console.log(idx, member.name));  // map 함수에서 제공하는 idx 값을 사용함
> 
> 
> // 빅터가 말하고자 한 것
> const members = [
>   { 
>     id: 0,
>     name: "빅터",
>     age: 28,
>   },
>   {
>     id: 1,
>     name: "샐리",
>     age: 100,
>   }
> ];
> 
> members.map(member => console.log(member.idx, member.name));  // map 함수에서 제공하는 idx 를 사용하지 않음
> ```
> 
> 이런 의미로 코멘트 준거였어요 ~

아하 그렇군요 이해했읍니다 예시 킹받지만 설명 감사드립니다 ^^..

2023-01-04 21:55 UTC, merged